spring.application.name=demo
spring.datasource.url=jdbc:postgresql://localhost:5433/nbp_db
spring.datasource.username=postgres
spring.datasource.password={DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
nbp.api.url = http://api.nbp.pl/api/

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true